version: '3.8'

services:
  nginx-fancyindex:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
    container_name: mirror-nginx-fancyindex 