server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Enable fancyindex for directory listings
    location / {
        try_files $uri $uri/ =404;
        
        # Enable fancy indexing
        fancyindex on;
        fancyindex_exact_size off;
				fancyindex_show_path off;
        fancyindex_localtime on;
        
        # Use custom header and footer
        fancyindex_header "/theme/header.html";
        fancyindex_footer "/theme/footer.html";
        
        # Hide theme directory from listings
        location /theme/ {
            internal;
        }
    }
} 
